"""empty message

Revision ID: 3bc7436527df
Revises: a5cffa318ac2
Create Date: 2025-10-19 08:10:30.033959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc7436527df'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anime_mal_id'), ['mal_id'], unique=True)

    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_mal_id'), ['mal_id'], unique=True)

    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('ep_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('aired_date', sa.String(length=50), nullable=True),
    sa.Column('forum_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episode_anime_id'), ['anime_id'], unique=False)

    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_type', 'resource_id', name='uq_favorite_user_res')
    )
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorite_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorite_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorite_resource_type'))
        batch_op.drop_index(batch_op.f('ix_favorite_resource_id'))

    op.drop_table('favorite')
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episode_anime_id'))

    op.drop_table('episode')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_mal_id'))

    op.drop_table('character')
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anime_mal_id'))

    op.drop_table('anime')
    # ### end Alembic commands ###
